[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "DeepTune"
authors = [{name = "Moayadeldin Hussain", email = "moayadeldin@gmail.com"}]
dynamic = ["1.0.0", "Advanced CLI tool automating multimodal Deep Learning applications"]
